# This is a basic workflow that is manually triggered

name: Push update

on:
  workflow_dispatch:
    inputs:
      loader_ver:
        description: 'Loader version'
        default: ''
      api_ver:
        description: 'API version'
        default: ''
      cli_ver:
        description: 'CLI version'
        default: ''

jobs:
  push:
    runs-on: ubuntu-latest

    steps:

      - id: json
        run: |
          content=`cat ./versions.json`
          echo "::set-output name=json::$content"
      - id: versions
        run: |
          echo "::set-output loader=${{github.event.inputs.loader_ver != '' && github.event.inputs.loader_ver || fromJson(steps.json.outputs.json).loader}}"
          echo "::set-output api=${{github.event.inputs.api_ver != '' && github.event.inputs.api_ver || fromJson(steps.json.outputs.json).api}}"
          echo "::set-output cli=${{github.event.inputs.cli_ver != '' && github.event.inputs.cli_ver || fromJson(steps.json.outputs.json).cli}}"

      - name: Update version info
        run: |
          echo ${{toJSON(steps.versions.outputs)}} > ./versions.json