# This is a basic workflow that is manually triggered

name: Push update

on:
  workflow_dispatch:
    inputs:
      loader_ver:
        description: 'Loader version'
        default: ''
      api_ver:
        description: 'API version'
        default: ''
      cli_ver:
        description: 'CLI version'
        default: ''

jobs:
  push:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
        with:
          repository: geode-sdk/suite
          path: suite
          submodules: recursive
          token: '${{ secrets.GEODE_BOT_PUSH_BIN_TOKEN }}'
      - run: git checkout nightly
        working-directory: ${{ github.workspace }}/suite

      - id: json
        run: |
          content=`cat ${{ github.workspace }}/suite/versions.json`
          echo "::set-output name=json::$content"
      - id: versions
        run: |
          echo "::set-output loader=${{github.event.inputs.loader_ver != '' && github.event.inputs.loader_ver || fromJson(steps.json.outputs.json).loader}}"
          echo "::set-output api=${{github.event.inputs.api_ver != '' && github.event.inputs.api_ver || fromJson(steps.json.outputs.json).api}}"
          echo "::set-output cli=${{github.event.inputs.cli_ver != '' && github.event.inputs.cli_ver || fromJson(steps.json.outputs.json).cli}}"

      - name: Update version info
        run: |
          echo ${{ steps.versions.outputs.api }}
          echo ${{ format('{{\"loader\": \"{0}\", \"api\": \"{1}\", \"cli\": \"{2}\"}}', steps.versions.outputs.loader, steps.versions.outputs.api, steps.versions.outputs.cli)  }} > ${{ github.workspace }}/suite/versions.json

      - name: Commit, push to suite, and merge
        working-directory: ${{ github.workspace }}/suite
        run: |
          git config --local user.email "${{ secrets.GEODE_BOT_EMAIL }}"
          git config --local user.name "GeodeBot"
          git add -A
          git commit -m "Stable update push"
          git push "https://GeodeBot:${{ secrets.GEODE_BOT_PUSH_BIN_TOKEN}}@github.com/geode-sdk/suite.git"
          git branch
          git checkout main
          git merge nightly
          git commit -m "Loader: ${{steps.versions.outputs.loader}} API: ${{steps.versions.outputs.api}} CLI: ${{steps.versions.outputs.cli}}"
          git push "https://GeodeBot:${{ secrets.GEODE_BOT_PUSH_BIN_TOKEN}}@github.com/geode-sdk/suite.git"
