name: Update SDK

on:
  push:
    branches: [ main ]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        repository: geode-sdk/sdk
        token: '${{ secrets.GEODE_BOT_PUSH_BIN_TOKEN }}'
    
    - name: Update bin
      working-directory: ${{ github.workspace }}/bin
      run: |
        git checkout main
        git pull origin main
          
    - name: Commit and push
      run: |
        git config --local user.email "${{ secrets.GEODE_BOT_EMAIL }}"
        git config --local user.name "GeodeBot"
        git commit -am "Auto-update from ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}"
        git push "https://GeodeBot:${{ secrets.GEODE_BOT_PUSH_BIN_TOKEN}}@github.com/geode-sdk/sdk.git" main
